// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/r2arma.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rwishart
arma::mat rwishart(unsigned int df, const arma::mat& S);
RcppExport SEXP _r2arma_rwishart(SEXP dfSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(rwishart(df, S));
    return rcpp_result_gen;
END_RCPP
}
// riwishart
arma::mat riwishart(unsigned int df, const arma::mat& S);
RcppExport SEXP _r2arma_riwishart(SEXP dfSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(riwishart(df, S));
    return rcpp_result_gen;
END_RCPP
}
// get_elements
arma::vec get_elements(const arma::mat& x, const arma::uvec& row_ind, const arma::uvec& col_ind);
RcppExport SEXP _r2arma_get_elements(SEXP xSEXP, SEXP row_indSEXP, SEXP col_indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type row_ind(row_indSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type col_ind(col_indSEXP);
    rcpp_result_gen = Rcpp::wrap(get_elements(x, row_ind, col_ind));
    return rcpp_result_gen;
END_RCPP
}
// rev_col_subset
arma::mat rev_col_subset(arma::mat x, unsigned int start, unsigned int end);
RcppExport SEXP _r2arma_rev_col_subset(SEXP xSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type start(startSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(rev_col_subset(x, start, end));
    return rcpp_result_gen;
END_RCPP
}
// rev_row_subset
arma::mat rev_row_subset(arma::mat x, unsigned int start, unsigned int end);
RcppExport SEXP _r2arma_rev_row_subset(SEXP xSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type start(startSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(rev_row_subset(x, start, end));
    return rcpp_result_gen;
END_RCPP
}
// reverse_vec
arma::vec reverse_vec(arma::vec x);
RcppExport SEXP _r2arma_reverse_vec(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(reverse_vec(x));
    return rcpp_result_gen;
END_RCPP
}
// field_to_matrix
arma::mat field_to_matrix(arma::field<arma::vec> x);
RcppExport SEXP _r2arma_field_to_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(field_to_matrix(x));
    return rcpp_result_gen;
END_RCPP
}
// sum_field_vec
double sum_field_vec(const arma::field<arma::vec>& x);
RcppExport SEXP _r2arma_sum_field_vec(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::vec>& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_field_vec(x));
    return rcpp_result_gen;
END_RCPP
}
// seq_int
arma::vec seq_int(long int a, long int b);
RcppExport SEXP _r2arma_seq_int(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long int >::type a(aSEXP);
    Rcpp::traits::input_parameter< long int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(seq_int(a, b));
    return rcpp_result_gen;
END_RCPP
}
// seq_default
arma::vec seq_default(long double from, long double to, long unsigned int length_out);
RcppExport SEXP _r2arma_seq_default(SEXP fromSEXP, SEXP toSEXP, SEXP length_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long double >::type from(fromSEXP);
    Rcpp::traits::input_parameter< long double >::type to(toSEXP);
    Rcpp::traits::input_parameter< long unsigned int >::type length_out(length_outSEXP);
    rcpp_result_gen = Rcpp::wrap(seq_default(from, to, length_out));
    return rcpp_result_gen;
END_RCPP
}
// seq_default_a
arma::vec seq_default_a(long double a, long double length_out);
RcppExport SEXP _r2arma_seq_default_a(SEXP aSEXP, SEXP length_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long double >::type a(aSEXP);
    Rcpp::traits::input_parameter< long double >::type length_out(length_outSEXP);
    rcpp_result_gen = Rcpp::wrap(seq_default_a(a, length_out));
    return rcpp_result_gen;
END_RCPP
}
// seq_along_cpp
arma::vec seq_along_cpp(const arma::vec& along_with);
RcppExport SEXP _r2arma_seq_along_cpp(SEXP along_withSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type along_with(along_withSEXP);
    rcpp_result_gen = Rcpp::wrap(seq_along_cpp(along_with));
    return rcpp_result_gen;
END_RCPP
}
// seq_len_cpp
arma::vec seq_len_cpp(long unsigned int length_out);
RcppExport SEXP _r2arma_seq_len_cpp(SEXP length_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long unsigned int >::type length_out(length_outSEXP);
    rcpp_result_gen = Rcpp::wrap(seq_len_cpp(length_out));
    return rcpp_result_gen;
END_RCPP
}
// diff_cpp
arma::vec diff_cpp(arma::vec x, unsigned int lag, unsigned int differences);
RcppExport SEXP _r2arma_diff_cpp(SEXP xSEXP, SEXP lagSEXP, SEXP differencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type differences(differencesSEXP);
    rcpp_result_gen = Rcpp::wrap(diff_cpp(x, lag, differences));
    return rcpp_result_gen;
END_RCPP
}
// ARMAtoMA_cpp
arma::vec ARMAtoMA_cpp(arma::vec ar, arma::vec ma, int lag_max);
RcppExport SEXP _r2arma_ARMAtoMA_cpp(SEXP arSEXP, SEXP maSEXP, SEXP lag_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type ar(arSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ma(maSEXP);
    Rcpp::traits::input_parameter< int >::type lag_max(lag_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(ARMAtoMA_cpp(ar, ma, lag_max));
    return rcpp_result_gen;
END_RCPP
}
// cfilter
arma::vec cfilter(arma::vec x, arma::vec filter, int sides, bool circular);
RcppExport SEXP _r2arma_cfilter(SEXP xSEXP, SEXP filterSEXP, SEXP sidesSEXP, SEXP circularSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type filter(filterSEXP);
    Rcpp::traits::input_parameter< int >::type sides(sidesSEXP);
    Rcpp::traits::input_parameter< bool >::type circular(circularSEXP);
    rcpp_result_gen = Rcpp::wrap(cfilter(x, filter, sides, circular));
    return rcpp_result_gen;
END_RCPP
}
// rfilter
arma::vec rfilter(arma::vec x, arma::vec filter, arma::vec init);
RcppExport SEXP _r2arma_rfilter(SEXP xSEXP, SEXP filterSEXP, SEXP initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type filter(filterSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init(initSEXP);
    rcpp_result_gen = Rcpp::wrap(rfilter(x, filter, init));
    return rcpp_result_gen;
END_RCPP
}
// ARMAacf_cpp
arma::vec ARMAacf_cpp(arma::vec ar, arma::vec ma, unsigned int lag_max);
RcppExport SEXP _r2arma_ARMAacf_cpp(SEXP arSEXP, SEXP maSEXP, SEXP lag_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type ar(arSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ma(maSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type lag_max(lag_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(ARMAacf_cpp(ar, ma, lag_max));
    return rcpp_result_gen;
END_RCPP
}
// dft_acf
arma::vec dft_acf(const arma::vec& x);
RcppExport SEXP _r2arma_dft_acf(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dft_acf(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_r2arma_rwishart", (DL_FUNC) &_r2arma_rwishart, 2},
    {"_r2arma_riwishart", (DL_FUNC) &_r2arma_riwishart, 2},
    {"_r2arma_get_elements", (DL_FUNC) &_r2arma_get_elements, 3},
    {"_r2arma_rev_col_subset", (DL_FUNC) &_r2arma_rev_col_subset, 3},
    {"_r2arma_rev_row_subset", (DL_FUNC) &_r2arma_rev_row_subset, 3},
    {"_r2arma_reverse_vec", (DL_FUNC) &_r2arma_reverse_vec, 1},
    {"_r2arma_field_to_matrix", (DL_FUNC) &_r2arma_field_to_matrix, 1},
    {"_r2arma_sum_field_vec", (DL_FUNC) &_r2arma_sum_field_vec, 1},
    {"_r2arma_seq_int", (DL_FUNC) &_r2arma_seq_int, 2},
    {"_r2arma_seq_default", (DL_FUNC) &_r2arma_seq_default, 3},
    {"_r2arma_seq_default_a", (DL_FUNC) &_r2arma_seq_default_a, 2},
    {"_r2arma_seq_along_cpp", (DL_FUNC) &_r2arma_seq_along_cpp, 1},
    {"_r2arma_seq_len_cpp", (DL_FUNC) &_r2arma_seq_len_cpp, 1},
    {"_r2arma_diff_cpp", (DL_FUNC) &_r2arma_diff_cpp, 3},
    {"_r2arma_ARMAtoMA_cpp", (DL_FUNC) &_r2arma_ARMAtoMA_cpp, 3},
    {"_r2arma_cfilter", (DL_FUNC) &_r2arma_cfilter, 4},
    {"_r2arma_rfilter", (DL_FUNC) &_r2arma_rfilter, 3},
    {"_r2arma_ARMAacf_cpp", (DL_FUNC) &_r2arma_ARMAacf_cpp, 3},
    {"_r2arma_dft_acf", (DL_FUNC) &_r2arma_dft_acf, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_r2arma(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
